repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    - id: check-added-large-files
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.37.1
    hooks:
    -   id: pyupgrade
        args: [--py38-plus]
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        language_version: python3.10
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
